name: test

on:
  push:
    branches:
      - main  # trigger bij elke push naar main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repo name
        run: echo "REPO_NAME=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ghcr.io/jaspervandevoort/${{ env.REPO_NAME }}:latest .

      - name: Push Docker image
        run: docker push ghcr.io/jaspervandevoort/${{ env.REPO_NAME }}:latest

